name: Abrir Site Automaticamente

on:
  workflow_dispatch:  # Permite execução manual no GitHub ✅
  schedule:
    - cron: '0 9 * * *'  # Executa todos os dias às 09:00
    - cron: '0 18 * * *'  # Executa todos os dias às 18:00

jobs:
  abrir_site:
    runs-on: ubuntu-latest
    steps:
      - name: Acessar o site
        run: curl -X GET "https://crmfelipe.streamlit.app/"
